[package]
name = "lockset_vault_provider"
version = "0.1.1"
edition = "2024"
description = "Vault Provider types for Lockset Vault"
license = "MIT"

[dependencies]
thiserror = "2.0.17"
async-trait = "0.1.89"
zeroize = "1.8.2"
